### ISSUE TITLE
myutils & requirements.txt

### ISSUE THREAD

**Issue by mherrmann3** [SalvIac/pysimulator#1]
Dear Salvatore,
I tried to install all required Python packages, but `myutils` is not officially recognized, so I suppose you wrote it yourself? Could you provide it? Otherwise, _pysimulator_ and _pyetas_ aren't usable. Thanks!

Btw: also I found that your `requirements.txt` should be slightly adjusted:

- drop `matlab=0.1`, it's not needed
- replace `openquake.engine==3.12` with `openquake.engine==3.12.1`
- replace `scikit_learn==0.24.2` with `scikit-learn==0.24.2` (note the dash)

Note that you don't need to pin the versions, see [stackoverflow.com](https://stackoverflow.com/questions/55052434/does-python-requirements-file-have-to-specify-version), unless you have certain compatibility requirements, or want to guarantee exact reproducibility.

**Comment by SalvIac** [comment]
Hi,

Many thanks for your interest in pyetas and pysimulator.

I apologise for the issue: I've just pushed a commit deleting the dependency on myutils and changing requirements.txt.

I'll do the same for pyetas shortly.

Sal

**Comment by mherrmann3** [comment]
Thank you Sal for your prompt update!

I managed to install all packages without conflict for Python v3.8 and a `requirements.txt` with all versions removed except for `openquake.engine`, i.e.:
```
tqdm
pandas
numba
scipy
numpy
matplotlib
shapely
Pillow
SALib
openquake.engine>=3.10
```
(prior openquake versions don't support `PointRupture`).

Note that I also dropped `pytz` and `scikit-learn`, which are not needed.
(`pyetas` itself, which is required for `pysimulator`, requires even less (no `Pillow` and `SALib`).)

Unfortunately, a significant amount of your source code got removed with your recent commit (all related to `app`), so that it's not possible anymore to use your tool to easy way (now, one has to figure out how to properly instantiate, run, and make use of `EtasSimulator`).

Related question: which of your `etas_simulator*.py` is the preferred one?

Thanks.

**Comment by mherrmann3** [comment]
Nice to e-meet you, too, Sal!

Thanks a lot for your effort to provide an example script. Highly useful!

I was wondering: so your tool's focus is to simulate aftershocks of one event (i.e., a scenario), but can it be used to simulate a full-scale synthetic catalog (i.e., background events and their aftershocks), like Felzer's [AftSimulator](https://web.archive.org/web/20200712004939/https://pasadena.wr.usgs.gov/office/kfelzer/AftSimulator.html), Ogata's [SASeis2006](https://www.ism.ac.jp/~ogata/Ssg/ssg_softwaresE.html) (Fortran), Harte's [PtProcess](https://www.jstatsoft.org/article/view/v035i08) (R), or Mizrahi's [ETAS implementation](https://github.com/lmizrahi/etas) (Python)?
After all, I see that the `EtasSimulator` class accepts a `background` keyword in `simul_options`.

This aspect would make your tool useful for so much more applications, especially because Python-based ETAS _simulators_ are rare (and one with spatially varying background rate doesn't exist yet).

Besides that, I hope you'll find the time & energy to continue developing your tool as an app.

Btw: not sure why you added `h5py` and `pyproj` to your `requirements.txt`, as they are not used.

**Comment by SalvIac** [comment]
Hi again,

To make sure everything worked fine, I tried to install pysimulator from scratch on another (clean) machine. h5py and pyproj are used internally by some of the openquake tools. Without explicitly installing them, example1.py doesn't work.

pysimulator is built to simulate full-scale synthetic catalogues. example1.py is only a specific case where the input catalogue only contains one event. If you are interested in longer catalogues, you only need to modify these two lists:

prev_datetimes = [sim_start]
prev_ruptures = [RuptureBuilder.init_point(mag=7., lon=0., lat=0., depth=10., rake=None, strike=None, dip=None)]

To contain as many events as you need. EtasSimulator will consider all of them.

EtasSimulator is much more complicated than the packages you mentioned. I've just reorganized the folder to look cleaner and avoid confusion. Please reinstall (or fetch origin).

I share below a (partial) list of features for EtasSimulator. I plan to release a series of python scripts to illustrate the features below, starting from example1.py to make more complicated examples. If you are interested, I can prioritize some examples over the others.

(1) simulation of events taking into account the geometry of the fault ruptures (as far as I am aware, other available packages do not have this feature). A few examples of fault geometry are shown in our paper Iacoletti et al. (2022). example1.py only takes a point source into account;
(2) simulation of various types of ETAS models, especially the one in our paper Iacoletti et al. (2022), including short-term incompleteness, truncated time and magnitude distributions. Other ETAS variations could be added in the future; I built pysimulator to be as flexible as possible (it's object-oriented);
(3) spatially varying background seismicity. Have a look at the static method "get_background_gridded" if you are interested.
(4) Zhuang-type background seismicity (this still needs some checking and tweaking);
(5) simulation of nodal planes and depths (example1.py only uses the default distributions).

Please keep in mind that, although the core structure of pysimulator will remain the same, pysimulator is still a work in progress: a few things here and there can change to improve usability, speed, or correct errors (if you find any, please open an issue here on GitHub, I'll be happy to look into that).

Many thanks for your interest,
Sal

**Comment by SalvIac** [comment]
Hi Marcus,

Thanks for your comments.

(1a) Thanks, I wasn't aware of all the AftSimulator's capabilities. As far as you know, can it handle a multi-fault rupture like Kaikoura 2016? If so, I'll have a look in the future.

(1b) I would say that UCERF3-ETAS is much more advanced/complicated than pysimulator. UCERF3-ETAS has several algorithms to revert a large aftershock to the most similar rupture in the UCERF3, which I simply couldn't do for a small paper like ours. That being said, I don't think UCERF3-ETAS is general enough to be applied outside California, and it's super tricky to adapt if you are not familiar with Java (I am not). pysimulator is simpler (although more complex than other available packages), and more flexible (I think, but we can disagree on this). 

(3) I'll send you example2.py in a day or so with the gridded background. Is this compatible with your schedule?

(4) Yes, it handles stochastic declustering like Zhuang 2011, but I didn't check/verify that the code works correctly as I didn't end up using it in the paper; long story short: it needs a bit of work, but the base code is there. It leverages the output of pyetas if stochastic declustering is used to calibrate ETAS. Let me know if you need this; I can work on it during the weekend.

(5) It is a 3d version of point 1, but it's not like the UCERF-ETAS. It is simpler because depths and nodal planes are assumed independent of the spatial PDF. This could be one of the improvements in the future, as long as I implement the same in pyetas. I wanted the pyetas and pysimulator to be as compatible as possible (i.e., the same models are available in pyetas for calibration and pysimulator for simulations). I don't think this is super common. For instance, I often see the fault geometry included in the simulations but not in the calibration. To me, this is a mistake (happy to disagree here). This is why pyetas and pysimulator are built to have two python-based (i.e., open) packages complementary to each other: both handling the same models, one for calibration, the other for simulations.

Many thanks, keep in touch
Sal

**Comment by mherrmann3** [comment]
Dear Sal,
please don't feel pressure from my comments! This is absolutely not intended; I only wanted to provide some feedback; there's absolutely no need to prioritize anything, especially not on weekends. It's already highly appreciated that you share your code and respond so quickly.

That being said, just my answers:
1a. No, AftSimulator only switches from a point to a planar source when a sampled magnitude overcomes a threshold (default: M6.5);
1b. I completely agree;
3. I'd highly welcome this; but again: no rush!
4. It's certainly good to have, as it doesn't require an extra/separate background model, but personally, I'm fine with point (3); Btw: in the doc string of this function, you refer to the wrong reference (Zhuang 2011 should be without 'et al.') ;-) This was a bit confusing at first.
5. Very good point. I wasn't aware of this. Thanks! Maybe you should also refer to the related `pyetas` in the README (and vice versia).

Just an idea that comes to my mind speaking about the README: it's perhaps worthwhile to list all functionality that is implemented (e.g., scenario-based/single-event simulation, short-term incompleteness, truncated MFD, ...) and not-yet-ready (e.g., stochastic declustering-based background, hazard, GUI, ...) of `py(etas)simulator` and `pyetas`. Just as an advertiser of what to expect from your tool, why to use it, and how it differs from the mass ;-)

Best,
Marcus

**Comment by SalvIac** [comment]
Thanks for the suggestions, nice discussion here.

Updated Zhuang 2011 reference and README.

Sal
